### ISSUE TITLE
Definição de multidisciplinar.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/processing#22]
De acordo com @abelpacker quando um periódico pertence a **3** (três) ou mais áreas do conhecimento, este deve ser definido com multidisciplinar.

Periódicos com até **2** (duas) áreas do conhecimento não devem ser definidos como multidisciplinar.

As tabulações devem ser corrigidas para atender a esta definição.

**Comment by abelpacker** [comment]
Quando o periódico é multidisciplinar, por ex, saúde, biológicas e sociais aplicadas, ele é contabilizado somente para multidisciplinar e não é contabilizado para as áreas específicas. No caso, o periódico não é contabilizado para saúde, biológicas e sociais aplicadas. Isso é importante para evitar o impacto de periódicos com apenas algunas artigos em uma área temática. Por exemplo, AABC publica poucos artigos em humanas e muitos artigos em outras áreas. Se contar como humanas o periódico chega a alterar o desempenho de humanas em % de artigos em inglês por exemplo. Atualmente, os periódicos multidisciplinares são 6 e como indicado acima não devem ser incluidos nas tabulações de outras áreas.
