### ISSUE TITLE
Agregar o ano de publicação do fascículo

### ISSUE THREAD

**Issue by ednilson** [scieloorg/processing#39]
Para o relatório "documents_dates" e outros se necessário seria importante agregar o ano de publicação que está na classe Issue:
Ex.:
http://articlemeta.scielo.org/api/v1/article/?code=S1806-11172019000200401
 {"article": {"publication_year": "2018"}}
 {"issue: {"publication_year": "2019"}}
Este periódico adota a modalidade **"publicação contínua"**. Mas o ano de publicação no registro artigo é 2018 e issue (que representa a legenda bibliográfica) é 2019.
A necessidade é para decidir a forma de analisar a produção com base no ano da legenda bibliográfica.

**Comment by ednilson** [comment]
O relatório "documents_dates.csv' está presente nos pacotes .zip das coleções que são baixado aqui:
https://analytics.scielo.org/w/reports
Ex. Brasil
https://static.scielo.org/tabs/tabs_bra.zip

**Comment by robertatakenaka** [comment]
@ednilson o ano da publicação do fascículo é o "document published at" (data do fascículo ), a partir da correção feita 
https://github.com/scieloorg/processing/pull/41
https://github.com/scieloorg/analytics/issues/138
